"use client";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { TProductDetails } from "@/types/TProductDetails";
import axios from "axios";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { toast } from "react-toastify";

export default function CreateProductPage() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<TProductDetails>();

    const { data: session, status } = useSession();
    const router = useRouter();


  const onSubmit = async (data: TProductDetails) => {
    try {
      let finalPhotoURL = "";

      // Handle image upload if file selected
      if (data.image && (data.image as unknown as FileList)?.length > 0) {
        const file = (data.image as unknown as FileList)[0];
        const formData = new FormData();
        formData.append("image", file);

        const imgResponse = await axios.post(
          `https://api.imgbb.com/1/upload?key=${process.env.NEXT_PUBLIC_IMAGE_API_KEY}`,
          formData,
        );
        finalPhotoURL = imgResponse.data.data.url;
      }

      // Prepare final product payload
      const newProduct: TProductDetails = {
        id: "", // generated by backend
        slug: data.title.toLowerCase().replace(/\s+/g, "-"),
        title: data.title,
        shortDescription: data.shortDescription,
        longDescription: data.longDescription,
        category: data.category,
        tags: data.tags
          ? (data.tags as unknown as string).split(",").map((t) => t.trim())
          : [],
        image: finalPhotoURL,
        gallery: data.gallery
          ? (data.gallery as unknown as string).split(",").map((g) => g.trim())
          : [],
        pricing: {
          currency: "USD",
          originalPrice: data.pricing?.originalPrice || 0,
          discountPrice: data.pricing?.discountPrice || 0,
          discountPercent: data.pricing?.discountPercent || 0,
        },
        stock: {
          status: data.stock?.status || "In Stock",
          quantity: data.stock?.quantity || 0,
        },
        badge: {
          text: "null",
          color: "null",
        },
        timeLeft: data.timeLeft || "",
        rating: {
          average: 0,
          totalReviews: 0,
        },
        features: data.features
          ? (data.features as unknown as string).split(",").map((f) => f.trim())
          : [],
        specifications: {
          plantCount: 0,
          potMaterial: "null",
          lightRequirement: "null",
          wateringFrequency: "null",
          petFriendly: false,
        },
        careInstructions: data.careInstructions
          ? (data.careInstructions as unknown as string)
              .split(",")
              .map((c) => c.trim())
          : [],
        delivery: {
          estimatedTime: "3-5 business days",
          shippingCost: "Free",
          returnPolicy: "7 days easy return",
        },
        seller: {
          name: "SmartGarden",
          verified: true,
          supportEmail: "support@smartgarden.com",
        },
        warranty: "null",
        createdAt: new Date().toISOString(),
      };

      const res = await axios.post("/api/products", newProduct);

      if (res) {
        toast.success("Product created successfully!");
        router.push("/products");
      } else {
        toast.error("Failed to create product");
      }
    } catch (err) {
      console.error(err);
      toast.error("Error creating product");
    }
  };


  if (status === "loading") return null;

  if (!session) {
    router.push("/login");
    return null;
  }

  return (
    <main className="flex items-center justify-center md:p-4">
      <Card className="w-full md:max-w-4xl">
        <CardHeader>
          <CardTitle>Create Product</CardTitle>
          <CardDescription>
            Fill in the details to create a new product
          </CardDescription>
        </CardHeader>

        <CardContent>
          <form onSubmit={handleSubmit(onSubmit)}>
            <div className="flex flex-col md:flex-row gap-5 pb-5">
              {/* LEFT GROUP */}
              <FieldGroup>
                <Field>
                  <FieldLabel>Title</FieldLabel>
                  <Input
                    placeholder="e.g. Indoor Plant Bundle"
                    {...register("title", { required: true })}
                  />
                </Field>

                <Field>
                  <FieldLabel>Short Description</FieldLabel>
                  <Textarea
                    placeholder="Enter short description"
                    {...register("shortDescription", { required: true })}
                  />
                </Field>

                <Field>
                  <FieldLabel>Long Description</FieldLabel>
                  <Textarea
                    placeholder="Enter long description"
                    {...register("longDescription", { required: true })}
                  />
                </Field>

                <Field>
                  <FieldLabel>Category</FieldLabel>
                  <Input
                    placeholder="e.g. Indoor Plants"
                    {...register("category", { required: true })}
                  />
                </Field>

                <Field>
                  <FieldLabel>Tags (comma separated)</FieldLabel>
                  <Input
                    placeholder="e.g. indoor, home decor, air purifying"
                    {...register("tags")}
                  />
                </Field>

                <Field>
                  <FieldLabel>Main Image</FieldLabel>
                  <Input
                    type="file"
                    {...register("image", { required: true })}
                  />
                </Field>

                <Field>
                  <FieldLabel>Gallery Images (comma separated)</FieldLabel>
                  <Input
                    type="text"
                    placeholder="url1, url2, url3"
                    {...register("gallery")}
                  />
                </Field>
              </FieldGroup>

              {/* RIGHT GROUP */}
              <FieldGroup>
                <Field>
                  <FieldLabel>Original Price</FieldLabel>
                  <Input
                    type="number"
                    placeholder="e.g. 149"
                    {...register("pricing.originalPrice")}
                  />
                </Field>

                <Field>
                  <FieldLabel>Discount Price</FieldLabel>
                  <Input
                    type="number"
                    placeholder="e.g. 89"
                    {...register("pricing.discountPrice")}
                  />
                </Field>

                <Field>
                  <FieldLabel>Discount %</FieldLabel>
                  <Input
                    type="number"
                    placeholder="e.g. 40"
                    {...register("pricing.discountPercent")}
                  />
                </Field>

                <Field>
                  <FieldLabel>Stock Status</FieldLabel>
                  <Input
                    placeholder="e.g. In Stock"
                    {...register("stock.status")}
                  />
                </Field>

                <Field>
                  <FieldLabel>Stock Quantity</FieldLabel>
                  <Input
                    type="number"
                    placeholder="e.g. 20"
                    {...register("stock.quantity")}
                  />
                </Field>

                <Field>
                  <FieldLabel>Time left</FieldLabel>
                  <Input
                    placeholder="e.g. 2h 45m left"
                    {...register("timeLeft")}
                  />
                </Field>

                <Field>
                  <FieldLabel>Care Instructions (comma separated)</FieldLabel>
                  <Input
                    placeholder="e.g. Avoid sunlight, Water weekly"
                    {...register("careInstructions")}
                  />
                </Field>

                <Field>
                  <FieldLabel>Features (comma separated)</FieldLabel>
                  <Input
                    placeholder="e.g. Care Guide Included, Free Delivery"
                    {...register("features")}
                  />
                </Field>
              </FieldGroup>
            </div>

            <Field className="mt-4 flex justify-end gap-2">
              <Button type="submit">Create Product</Button>
            </Field>
          </form>
        </CardContent>
      </Card>
    </main>
  );
}
